language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew
  - chmod +x push.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
#  - ./push.sh

 # cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
